server:
  port: 1234
eureka:
  instance:
    hostname: eureka-server
  client:
    register-with-eureka: false
    fetch-registry: false
  service-url:
    defaultZone: http://eureka-server:1234/erueka/

